version: '3.8'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db 
    environment:
      - "DJANGO_SECRET_KEY=wqb@h@nqqw^l#^f%w8+cmyqxr_%6v1!3$$=6w$$t!58p2yqed4s7"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0" 
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False" 
      - "DJANGO_SECURE_HSTS_PRELOAD=False" 

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: