# Generated by Django 3.1.14 on 2022-06-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220630_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
